### ISSUE TITLE
Node not started on your end

### ISSUE THREAD

**Issue by le2Ks** [Julicraft44/Lucycoin#1]
Hello cat lover!

I think your node is not started on your side,

The seed is well typed in the net.cpp file: 177.233.81.45  in hex code

But the connection is not going through, you've stopped it perhaps?

Thank you!

**Comment by Julicraft44** [comment]
Oh is it reversed?
It should be up and running on the main network!
Try to add the node via the config:
addnode=45.81.233.177

**Comment by Julicraft44** [comment]
Should be fixed now!

**Comment by le2Ks** [comment]
Awesome thanks!
