### ISSUE TITLE
Need help! - Building coin for Windows is not working.

### ISSUE THREAD

**Issue by Julicraft44** [Julicraft44/Lucycoin#2]
If you are into this and wanna help me, please reply to this issue!
It's stuck here and I don't know why:
./bin/gbuild ../Lucycoin/contrib/gitian-descriptors/deps-win32.yml

I had to change some values in the deps-win32.yml file, like the suites from precise to trusty and the libfaketime path to some other dirs...

**Comment by le2Ks** [comment]
Hi, i have no idea ive never did it that way, i use mingw to crosscompile Windows binaries into a Linux server. Have you heard of it?

**Comment by Julicraft44** [comment]
No I didn't heard about that.
Do you know how to compile for Windows with this? Is this even possible?

**Comment by le2Ks** [comment]
Hi, yes absolutely it is possible. Make a quick research on google about mingw crosscompile there are great tutorials
I can compile them for you let me know also

**Comment by Julicraft44** [comment]
Okay, thank you. I will take a look at it!

**Comment by le2Ks** [comment]
Awesome okk, hey wanna make a discord group for the project? or telegram, will be easier to talk with

**Comment by Julicraft44** [comment]
I actuelly created a Discord Server, but I had no time to configure. I think I will do it next week.

**Comment by le2Ks** [comment]
Hey what was the node already i didnt note it before deletion of issue

**Comment by le2Ks** [comment]
Okk np lets go in the discord even if not configured that will still better than chatting here hehe

**Comment by Julicraft44** [comment]
I commited it into the readme

**Comment by le2Ks** [comment]
Ok
